stages:
  - build
  - deploy

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA

before_script:
  - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin

build:dev:
  stage: build
  script:
    - docker build -f Dockerfile -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
  tags:
    - front-build

deploy:dev:
  stage: deploy
  before_script:
    - cp $DEV_ENV_FILE .env
  script:
    - docker stack deploy -c stack.yml crm_front --prune --with-registry-auth
  tags:
    - front-deploy
