services:
  crm-front:
    image: ${IMAGE_TAG}
    env_file:
      - .env
    deploy:
      replicas: 1
      restart_policy:
        condition: none
    volumes:
      - frontend-data:/app/dist
    networks: [nginx-public]

networks:
  nginx-public:
    external: true

volumes:
  frontend-data:
